version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cfmc-web-app
    ports:
      - "3000:3000"
    volumes:
      - .:/src/app
      - /src/app/node_modules
